stages:
  - test
  - build
  - push

# --------------------
# TEST STAGE
# --------------------
test:
  stage: test
  image: node:25-alpine
  services:
    - name: postgres:16-alpine
      alias: db
  variables:
    POSTGRES_DB: testdb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    DATABASE_URL: postgres://postgres:postgres@db:5432/testdb
  script:
    - apk add --no-cache postgresql-client
    - until pg_isready -h db -U postgres; do sleep 1; done
    - npm ci
    - npm run build
    - npm test
  rules:
    - if: '$CI_COMMIT_BRANCH'

# --------------------
# BUILD STAGE
# --------------------
build_image:
  stage: build
  image: docker:24
  services:
    - name: docker:24-dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'

# --------------------
# PUSH STAGE
# --------------------
push_dev:
  stage: push
  image: docker:24
  services:
    - name: docker:24-dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
